export default {
    use:true,
    defaultStyle:{
        "border-radius":"",
        "background-color":"",
        "width":"",
        "height":"",
        "border":"",
        "color":"",
        "font-size":"",
    },
    success:{
        "background-color":"#39b54a",
    },
    warning:{
        "background-color":"#fbbd08",
    },
    error:{
        "background-color":"#e54d42",
    },
}