export default {
    use:true,
    defaultStyle:{
        bordeRadius:"",
        backgroundColor:"",
        width:"",
        height:"",
        border:"",
        colo:"",
        fontSize:"",
    },
    success:{
        backgroundColor:"#39b54a",
    },
    warning:{
        backgroundColor:"#fbbd08",
    },
    error:{
        backgroundColor:"#e54d42",
    },
}