Page({

  /**
   * 页面的初始数据
   */
  data: {
        navBarOptions:{
            barTitleText:"颜色",
            frontColor:"#000000"
        },
        normalList:[
            {
                color:"red",
                value:"#e54d42"
            },
            {
                color:"orange",
                value:"#ff9900"
            },
            {
                color:"yellow",
                value:"#fbbd08"
            },
            {
                color:"olive",
                value:"#8dc63f"
            },
            {
                color:"green",
                value:"#39b54a"
            },
            {
                color:"cyan",
                value:"#1cbbb4"
            },
            {
                color:"blue",
                value:"#0081ff"
            },
            {
                color:"purple",
                value:"#6739b6"
            },
            {
                color:"mauve",
                value:"#9c26b0"
            },
            {
                color:"pink",
                value:"#e03997"
            },
            {
                color:"brown",
                value:"#a5673f"
            },
            {
                color:"redLight",
                value:"#fadbd9"
            },
            {
                color:"orangeLight",
                value:"#fde6d2"
            },
            {
                color:"yellowLight",
                value:"#fef2ce"
            },
            {
                color:"oliveLight",
                value:"#e8f4d9"
            },
            {
                color:"greenLight",
                value:"#d7f0db"
            },
            {
                color:"cyanLight",
                value:"#d2f1f0"
            },
            {
                color:"purpleLight",
                value:"#e1d7f0"
            },
            {
                color:"mauveLight",
                value:"#ebd4ef"
            },
            {
                color:"pinkLight",
                value:"#f9d7ea"
            },
            {
                color:"brownLight",
                value:"#ede1d9"
            },
        ],
  },
  /**
   * 生命周期函数--监听页面加载
   */
  onLoad(options) {

  },
})